services:
  # Flask App
  flask_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - monitoring
    restart: always
    
  # Prometheus - Metrics collection
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring
    restart: always
    depends_on:
      - flask_app
      - cadvisor

  # Grafana - Visualization
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin # NOT SAFE FOR PRODUCTION!!!
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    restart: always
    depends_on:
      - prometheus
  
  # cAdvisor - Container metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    restart: always

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
